[package]
name = "diffusion-models"
version = "0.1.0"
edition = "2021"
[dependencies]
diffusion-types = { path = "../diffusion-types" }
titan-hal = { git = "https://github.com/game-gpt/titan.rs.git", rev = "8942849", package = "titan-hal" }
titan-tensor = { git = "https://github.com/game-gpt/titan.rs.git", rev = "8942849", package = "titan-tensor" }
safetensors = "0.8.0"
half = "2.7"
serde_json.workspace = true
